### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by dana-p** [james-woo/athelite#15]
Hi James, 

Great app, I have a couple feature requests/issues for the app: 
- Could the graph include today as well? It seems like it goes until yesterday. 
- Notifications -- if I have a workout today and I open the app, I immediately get a notification saying "See today's workout". Since I've opened the app, I don't really want to see today's workout. Perhaps you could have like an option for that notification for the time when it can appear. For example, I workout every day around 5:30. If I got the notification around 5:30 on the days I have workouts, then I could quickly open up the app without having to look for it. 
- When I click graph, all my exercises are listed. I see some 1 rep max'es . Some of them are 0 lbs as the rep max, even though I've done workouts. The numbers are displayed correctly for those exercises in the templates though. 

Anyway, other than that I've enjoyed using it this past week! Keep up the great work :D 

Dana

**Comment by james-woo** [comment]
Thanks for the feedback! We have opened up these issues here:
#16 and #17
